 require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/mng_reservations", type: :request do
  # MngReservation. As you add validations to MngReservation, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      MngReservation.create! valid_attributes
      get mng_reservations_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      mng_reservation = MngReservation.create! valid_attributes
      get mng_reservation_url(mng_reservation)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_mng_reservation_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "render a successful response" do
      mng_reservation = MngReservation.create! valid_attributes
      get edit_mng_reservation_url(mng_reservation)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new MngReservation" do
        expect {
          post mng_reservations_url, params: { mng_reservation: valid_attributes }
        }.to change(MngReservation, :count).by(1)
      end

      it "redirects to the created mng_reservation" do
        post mng_reservations_url, params: { mng_reservation: valid_attributes }
        expect(response).to redirect_to(mng_reservation_url(MngReservation.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new MngReservation" do
        expect {
          post mng_reservations_url, params: { mng_reservation: invalid_attributes }
        }.to change(MngReservation, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post mng_reservations_url, params: { mng_reservation: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested mng_reservation" do
        mng_reservation = MngReservation.create! valid_attributes
        patch mng_reservation_url(mng_reservation), params: { mng_reservation: new_attributes }
        mng_reservation.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the mng_reservation" do
        mng_reservation = MngReservation.create! valid_attributes
        patch mng_reservation_url(mng_reservation), params: { mng_reservation: new_attributes }
        mng_reservation.reload
        expect(response).to redirect_to(mng_reservation_url(mng_reservation))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        mng_reservation = MngReservation.create! valid_attributes
        patch mng_reservation_url(mng_reservation), params: { mng_reservation: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested mng_reservation" do
      mng_reservation = MngReservation.create! valid_attributes
      expect {
        delete mng_reservation_url(mng_reservation)
      }.to change(MngReservation, :count).by(-1)
    end

    it "redirects to the mng_reservations list" do
      mng_reservation = MngReservation.create! valid_attributes
      delete mng_reservation_url(mng_reservation)
      expect(response).to redirect_to(mng_reservations_url)
    end
  end
end
